[keys]
# CircleCI
circleci_org_slug = "moshiaiz" # Akin to github/your_user_name
circleci_org_id = "05126b82-4e9f-4606-baf2-0b25df351e01" # The ID of your org - get it in org settings
circleci_token = "e178324c2e62afeaeabaafa246f9e9ca21569d05" # Generate in CircleCI account settings

# Third party
snyk_token = "14569e62-9e3a-488c-9dde-2a0b40309f3f"
docker_login = "moshiaiz"
docker_token = "dckr_pat_-QgBWv48MNXhh7TSPJklOYNIm-4"
tf_cloud_key = "j4mj7sSNibNZMw.atlasv1.cCZqiDgoynO6gyjzq0jiNFnMIxQoymBvo8PeFMc6Vl9wPGIF29NoCdZjCabIyR0NrGY"
digitalocean_token = "dop_v1_ae0651d32a8c67d31ab6fc204e66e475430f10bd634df1ae2eb0aa67800b834d"
